django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("destinations/", include("destinations.urls")),
    path("", include("pages.urls")),
    path("attractions/", include("attractions.urls")),
]
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("about/", AboutPageView.as_view(), name="about"),
]

attractions/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from destinations.models import Destination


# Create your models here.
class Attraction(models.Model):
    location = models.ForeignKey(
        Destination,
        on_delete=models.CASCADE,
    )
    name = models.CharField(primary_key=True, max_length=255)
    description = models.TextField(blank=False)
    address = models.TextField()
    rating = models.IntegerField(
        blank=False, validators=[MaxValueValidator(5), MinValueValidator(1)]
    )
    tags = models.TextField()
    numberReviews = models.IntegerField(default=1)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    image = models.ImageField(
        default="staticfiles/img/dest/no_image.jpg", upload_to="static/img/attr/"
    )

    def __str__(self):
        return self.name

    def get_url(self):
        return self.location.get_absolute_url()

    def get_absolute_url(self):
        return reverse("attraction_detail", kwargs={"pk": self.pk})


class AttractionComment(models.Model):
    attraction = models.ForeignKey(Attraction, on_delete=models.CASCADE)
    comment = models.CharField(max_length=255)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("attraction_list")

templates/attraction_detail.html
{% load crispy_forms_tags %}
{% load static %}

{% block attraction_detail %}
<!DOCTYPE html>
<html lang="en-US" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <!-- ===============================================-->
  <!--    Document Title-->
  <!-- ===============================================-->
  <title>Destination Darling</title>


  <!-- ===============================================-->
  <!--    Favicons-->
  <!-- ===============================================-->
  <link rel="icon" type="image/png" sizes="20x20" href="{% static 'img/favicons/favicon-512x512.png' %}">
  <meta name="theme-color" content="#ffffff">



  <!-- ===============================================-->
  <!--    Stylesheets-->
  <!-- ===============================================-->
  <link href="{% static 'css/theme.css' %}" rel="stylesheet" />


  <!-- ===============================================-->
  <!--     Mouse Sparkle Effect-->
  <!-- ===============================================-->
  <script type="text/javascript">
    // <![CDATA[
    var colour = "#000000";
    var sparkles = 120;/****************************
  *  Tinkerbell Magic Sparkle *
  * (c) 2005 mf2fm web-design *
  *  http://www.mf2fm.com/rv  *
  * DON'T EDIT BELOW THIS BOX *
  ****************************/
    var x = ox = 400;
    var y = oy = 300;
    var swide = 800;
    var shigh = 600;
    var sleft = sdown = 0;
    var tiny = new Array();
    var star = new Array();
    var starv = new Array();
    var starx = new Array();
    var stary = new Array();
    var tinyx = new Array();
    var tinyy = new Array();
    var tinyv = new Array(); window.onload = function () {
      if (document.getElementById) {
        var i, rats, rlef, rdow;
        for (var i = 0; i < sparkles; i++) {
          var rats = createDiv(3, 3);
          rats.style.visibility = "hidden";
          document.body.appendChild(tiny[i] = rats);
          starv[i] = 0;
          tinyv[i] = 0;
          var rats = createDiv(5, 5);
          rats.style.backgroundColor = "transparent";
          rats.style.visibility = "hidden";
          var rlef = createDiv(1, 5);
          var rdow = createDiv(5, 1);
          rats.appendChild(rlef);
          rats.appendChild(rdow);
          rlef.style.top = "2px";
          rlef.style.left = "0px";
          rdow.style.top = "0px";
          rdow.style.left = "2px";
          document.body.appendChild(star[i] = rats);
        }
        set_width();
        sparkle();
      }
    }
    function sparkle() {
      var c;
      if (x != ox || y != oy) {
        ox = x;
        oy = y;
        for (c = 0; c < sparkles; c++) if (!starv[c]) {
          star[c].style.left = (starx[c] = x) + "px";
          star[c].style.top = (stary[c] = y) + "px";
          star[c].style.clip = "rect(0px, 5px, 5px, 0px)";
          star[c].style.visibility = "visible";
          starv[c] = 50;
          break;
        }
      }
      for (c = 0; c < sparkles; c++) {
        if (starv[c]) update_star(c);
        if (tinyv[c]) update_tiny(c);
      }
      setTimeout("sparkle()", 40);
    } function update_star(i) {
      if (--starv[i] == 25) star[i].style.clip = "rect(1px, 4px, 4px, 1px)";
      if (starv[i]) {
        stary[i] += 1 + Math.random() * 3;
        if (stary[i] < shigh + sdown) {
          star[i].style.top = stary[i] + "px";
          starx[i] += (i % 5 - 2) / 5;
          star[i].style.left = starx[i] + "px";
        }
        else {
          star[i].style.visibility = "hidden";
          starv[i] = 0;
          return;
        }
      }
      else {
        tinyv[i] = 50;
        tiny[i].style.top = (tinyy[i] = stary[i]) + "px";
        tiny[i].style.left = (tinyx[i] = starx[i]) + "px";
        tiny[i].style.width = "2px";
        tiny[i].style.height = "2px";
        star[i].style.visibility = "hidden";
        tiny[i].style.visibility = "visible"
      }
    } function update_tiny(i) {
      if (--tinyv[i] == 25) {
        tiny[i].style.width = "1px";
        tiny[i].style.height = "1px";
      }
      if (tinyv[i]) {
        tinyy[i] += 1 + Math.random() * 3;
        if (tinyy[i] < shigh + sdown) {
          tiny[i].style.top = tinyy[i] + "px";
          tinyx[i] += (i % 5 - 2) / 5;
          tiny[i].style.left = tinyx[i] + "px";
        }
        else {
          tiny[i].style.visibility = "hidden";
          tinyv[i] = 0;
          return;
        }
      }
      else tiny[i].style.visibility = "hidden";
    } document.onmousemove = mouse;
    function mouse(e) {
      set_scroll();
      y = (e) ? e.pageY : event.y + sdown;
      x = (e) ? e.pageX : event.x + sleft;
    } function set_scroll() {
      if (typeof (self.pageYOffset) == "number") {
        sdown = self.pageYOffset;
        sleft = self.pageXOffset;
      }
      else if (document.body.scrollTop || document.body.scrollLeft) {
        sdown = document.body.scrollTop;
        sleft = document.body.scrollLeft;
      }
      else if (document.documentElement && (document.documentElement.scrollTop || document.documentElement.scrollLeft)) {
        sleft = document.documentElement.scrollLeft;
        sdown = document.documentElement.scrollTop;
      }
      else {
        sdown = 0;
        sleft = 0;
      }
    } window.onresize = set_width;
    function set_width() {
      if (typeof (self.innerWidth) == "number") {
        swide = self.innerWidth;
        shigh = self.innerHeight;
      }
      else if (document.documentElement && document.documentElement.clientWidth) {
        swide = document.documentElement.clientWidth;
        shigh = document.documentElement.clientHeight;
      }
      else if (document.body.clientWidth) {
        swide = document.body.clientWidth;
        shigh = document.body.clientHeight;
      }
    } function createDiv(height, width) {
      var div = document.createElement("div");
      div.style.position = "absolute";
      div.style.height = height + "px";
      div.style.width = width + "px";
      div.style.overflow = "hidden";
      div.style.backgroundColor = colour;
      return (div);
    }
    // ]]>
  </script>

</head>

<!-- ===============================================-->
<!--    Stars Widget-->
<!-- ===============================================-->
<script type="text/javascript">(function (d, t, e, m) {

    // Async Rating-Widget initialization.
    window.RW_Async_Init = function () {

      RW.init({
        huid: "494656",
        uid: "dca821da227f83268174135169857036",
        source: "website",
        options: {
          "advanced": {
            "font": {
              "hover": {
                "color": "#B13F94"
              },
              "size": "18px",
              "bold": true,
              "color": "#B13F94",
              "type": "\"Lucida Sans Unicode\""
            }
          },
          "size": "large",
          "label": {
            "background": "#F4B6DB"
          },
          "style": "flat_yellow",
          "isDummy": false
        }
      });
      RW.render();
    };
    // Append Rating-Widget JavaScript library.
    var rw, s = d.getElementsByTagName(e)[0], id = "rw-js",
      l = d.location, ck = "Y" + t.getFullYear() +
        "M" + t.getMonth() + "D" + t.getDate(), p = l.protocol,
      f = ((l.search.indexOf("DBG=") > -1) ? "" : ".min"),
      a = ("https:" == p ? "secure." + m + "js/" : "js." + m);
    if (d.getElementById(id)) return;
    rw = d.createElement(e);
    rw.id = id; rw.async = true; rw.type = "text/javascript";
    rw.src = p + "//" + a + "external" + f + ".js?ck=" + ck;
    s.parentNode.insertBefore(rw, s);
  }(document, new Date(), "script", "rating-widget.com/"));
</script>

<body>
  <main class="main" id="top">
    <nav class="navbar navbar-expand-lg navbar-light navbar-toggler top py-5 d-block"
      data-navbar-on-scroll="data-navbar-on-scroll">
      <div class="container"><a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'img/DDLogo.png' %}"
            height="75" alt="logo" /></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
            class="navbar-toggler-icon">
          </span></button>
        <div class="collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto pt-2 pt-lg-0 font-base align-items-lg-center align-items-start">
            <li class="nav-item px-3 px-xl-4"><a class="nav-link fw-medium" aria-current="page"
                href="{% url 'attraction_new' %}">+ New Attraction</a></li>
            <li class="nav-item px-3 px-xl-4"><a class="nav-link fw-medium" aria-current="page"
                href="{% url 'destination_list' %}">Destinations</a></li>
            <li class="nav-item px-3 px-xl-4"><a class="nav-link fw-medium" aria-current="page"
                href="{% url 'about' %}">About
                Us</a></li>
            <li class="nav-item px-3 px-xl-4"><a class="nav-link fw-medium" aria-current="page"
                href="{% url 'user_profile' %}">
                {{ user.username }} {{ user.status }}</a></li>
            <li class="nav-item dropdown px-3 px-lg-0"> <a
                class="d-inline-block ps-0 py-2 pe-3 text-decoration-none dropdown-toggle fw-medium" href="#"
                id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">User Settings</a>
              <ul class="dropdown-menu dropdown-menu-end border-0 shadow-lg" style="border-radius:0.3rem;"
                aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                </li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <div class="container">
      <div class="position-absolute start-100 bottom-0 translate-middle-x d-none d-xl-block ms-xl-n4"></div>
      <div class="mb-7 text-center">
        <h3 class="fs-xl-10 fs-lg-8 fs-7 fw-bold font-cursive text-capitalize">{{ attraction.name }}</h3>
        <img class="card-img-top" src="{{ attraction.image.url }}" alt="attraction-img" />
        <p>by {{ attraction.author }} | {{ attraction.date }}</p>
        <h4 class="fw-bold text-secondary mb-3">{{ attraction.description }}</h4>
      </div>

      <div class="row">
        <div class="col-md-5 col-lg-6 text-md-start text-center">
          <h4 class="fw-bold text-secondary mb-3">Comments about {{ attraction }}</h4>
          {% for attractioncomment in attraction.attractioncomment_set.all %}
          <p>{{ attractioncomment }} &middot; {{ attractioncomment.author }} &middot;
            {{ attractioncomment.author.status}}</p>
          {% endfor %}
        </div>
        <div class="col-md-5 col-lg-6 text-md-start text-center">
          <h4>Add a comment</h4>
          <div class="rw-ui-container"></div>
          <form action="" method="post"> {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success ml-2" type="submit">Save</button>
          </form>
        </div>
      </div>


      <div class="row align-items-center py-5">
        <div class="mb-7 text-center">
          <div> {% if attraction.author.pk == request.user.pk %}
            <p><a href="{% url 'attraction_edit'  attraction.pk %}">Edit </a><a
                href="{% url 'attraction_delete' attraction.pk %}"> Delete</a></p>
          </div>
          {% endif %}
          <div class="row align-items-center py-3"></div>
          <p>Back to <a href="{{ attraction.get_url }}/attractions/">All Attractions</a>.</p>
        </div>
      </div>
      </section>
  </main>
</body>
<div class="py-5 text-center">
  <p class="mb-0 text-secondary fs--1 fw-medium">All rights reserved@darling.co </p>
</div>

<!-- ===============================================-->
<!-- JavaScriptes-->
<!-- ===============================================-->
<script src="{% static 'vendors/@popperjs/popper.min.js' %}"></script>
<script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'vendors/is/is.min.js' %}"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
<script src="{% static 'vendors/fontawesome/all.min.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>
<link
  href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&amp;family=Volkhov:wght@700&amp;display=swap"
  rel="stylesheet">
{% endblock attraction_detail %}

templates/attraction_list.html
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en-US" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- ===============================================-->
    <!--    Document Title-->
    <!-- ===============================================-->
    <title>Destination Darling</title>


    <!-- ===============================================-->
    <!--    Favicons-->
    <!-- ===============================================-->
    <link rel="icon" type="image/png" sizes="20x20" href="{% static 'img/favicons/favicon-512x512.png' %}">
    <meta name="theme-color" content="#ffffff">


    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" />


    <!-- ===============================================-->
    <!--     Mouse Sparkle Effect-->
    <!-- ===============================================-->
    <script type="text/javascript">
        // <![CDATA[
        var colour = "#000000";
        var sparkles = 120;/****************************
    *  Tinkerbell Magic Sparkle *
    * (c) 2005 mf2fm web-design *
    *  http://www.mf2fm.com/rv  *
    * DON'T EDIT BELOW THIS BOX *
    ****************************/
        var x = ox = 400;
        var y = oy = 300;
        var swide = 800;
        var shigh = 600;
        var sleft = sdown = 0;
        var tiny = new Array();
        var star = new Array();
        var starv = new Array();
        var starx = new Array();
        var stary = new Array();
        var tinyx = new Array();
        var tinyy = new Array();
        var tinyv = new Array(); window.onload = function () {
            if (document.getElementById) {
                var i, rats, rlef, rdow;
                for (var i = 0; i < sparkles; i++) {
                    var rats = createDiv(3, 3);
                    rats.style.visibility = "hidden";
                    document.body.appendChild(tiny[i] = rats);
                    starv[i] = 0;
                    tinyv[i] = 0;
                    var rats = createDiv(5, 5);
                    rats.style.backgroundColor = "transparent";
                    rats.style.visibility = "hidden";
                    var rlef = createDiv(1, 5);
                    var rdow = createDiv(5, 1);
                    rats.appendChild(rlef);
                    rats.appendChild(rdow);
                    rlef.style.top = "2px";
                    rlef.style.left = "0px";
                    rdow.style.top = "0px";
                    rdow.style.left = "2px";
                    document.body.appendChild(star[i] = rats);
                }
                set_width();
                sparkle();
            }
        }
        function sparkle() {
            var c;
            if (x != ox || y != oy) {
                ox = x;
                oy = y;
                for (c = 0; c < sparkles; c++) if (!starv[c]) {
                    star[c].style.left = (starx[c] = x) + "px";
                    star[c].style.top = (stary[c] = y) + "px";
                    star[c].style.clip = "rect(0px, 5px, 5px, 0px)";
                    star[c].style.visibility = "visible";
                    starv[c] = 50;
                    break;
                }
            }
            for (c = 0; c < sparkles; c++) {
                if (starv[c]) update_star(c);
                if (tinyv[c]) update_tiny(c);
            }
            setTimeout("sparkle()", 40);
        } function update_star(i) {
            if (--starv[i] == 25) star[i].style.clip = "rect(1px, 4px, 4px, 1px)";
            if (starv[i]) {
                stary[i] += 1 + Math.random() * 3;
                if (stary[i] < shigh + sdown) {
                    star[i].style.top = stary[i] + "px";
                    starx[i] += (i % 5 - 2) / 5;
                    star[i].style.left = starx[i] + "px";
                }
                else {
                    star[i].style.visibility = "hidden";
                    starv[i] = 0;
                    return;
                }
            }
            else {
                tinyv[i] = 50;
                tiny[i].style.top = (tinyy[i] = stary[i]) + "px";
                tiny[i].style.left = (tinyx[i] = starx[i]) + "px";
                tiny[i].style.width = "2px";
                tiny[i].style.height = "2px";
                star[i].style.visibility = "hidden";
                tiny[i].style.visibility = "visible"
            }
        } function update_tiny(i) {
            if (--tinyv[i] == 25) {
                tiny[i].style.width = "1px";
                tiny[i].style.height = "1px";
            }
            if (tinyv[i]) {
                tinyy[i] += 1 + Math.random() * 3;
                if (tinyy[i] < shigh + sdown) {
                    tiny[i].style.top = tinyy[i] + "px";
                    tinyx[i] += (i % 5 - 2) / 5;
                    tiny[i].style.left = tinyx[i] + "px";
                }
                else {
                    tiny[i].style.visibility = "hidden";
                    tinyv[i] = 0;
                    return;
                }
            }
            else tiny[i].style.visibility = "hidden";
        } document.onmousemove = mouse;
        function mouse(e) {
            set_scroll();
            y = (e) ? e.pageY : event.y + sdown;
            x = (e) ? e.pageX : event.x + sleft;
        } function set_scroll() {
            if (typeof (self.pageYOffset) == "number") {
                sdown = self.pageYOffset;
                sleft = self.pageXOffset;
            }
            else if (document.body.scrollTop || document.body.scrollLeft) {
                sdown = document.body.scrollTop;
                sleft = document.body.scrollLeft;
            }
            else if (document.documentElement && (document.documentElement.scrollTop || document.documentElement.scrollLeft)) {
                sleft = document.documentElement.scrollLeft;
                sdown = document.documentElement.scrollTop;
            }
            else {
                sdown = 0;
                sleft = 0;
            }
        } window.onresize = set_width;
        function set_width() {
            if (typeof (self.innerWidth) == "number") {
                swide = self.innerWidth;
                shigh = self.innerHeight;
            }
            else if (document.documentElement && document.documentElement.clientWidth) {
                swide = document.documentElement.clientWidth;
                shigh = document.documentElement.clientHeight;
            }
            else if (document.body.clientWidth) {
                swide = document.body.clientWidth;
                shigh = document.body.clientHeight;
            }
        } function createDiv(height, width) {
            var div = document.createElement("div");
            div.style.position = "absolute";
            div.style.height = height + "px";
            div.style.width = width + "px";
            div.style.overflow = "hidden";
            div.style.backgroundColor = colour;
            return (div);
        }
        // ]]>
    </script>

</head>
<main class="main" id="top">
    <nav class="navbar navbar-expand-lg navbar-light navbar-toggler fixed-top py-5 d-block"
        data-navbar-on-scroll="data-navbar-on-scroll">
        <div class="container"><a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'img/DDLogo.png' %}"
                    height="75" alt="logo" /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon">
                </span></button>
            <div class="collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto pt-2 pt-lg-0 font-base align-items-lg-center align-items-start">
                    <li class="nav-item px-3 px-xl-4"><a class="nav-link fw-medium" aria-current="page"
                            href="{% url 'attraction_new' %}">+ New Attraction</a></li>
                    <li class="nav-item px-3 px-xl-4"><a class="nav-link fw-medium" aria-current="page"
                            href="{% url 'about' %}">About
                            Us</a></li>
                    <li class="nav-item px-3 px-xl-4"><a class="nav-link fw-medium" aria-current="page"
                            href="{% url 'user_profile' %}">{{ user.username }} {{ user.status }}</a></li>
                    <li class="nav-item dropdown px-3 px-lg-0"> <a
                            class="d-inline-block ps-0 py-2 pe-3 text-decoration-none dropdown-toggle fw-medium"
                            href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">User Settings</a>
                        <ul class="dropdown-menu dropdown-menu-end border-0 shadow-lg" style="border-radius:0.3rem;"
                            aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <section style="padding-top: 7rem;">
        <div class="bg-holder">
        </div>
        <div class="container">
            <div class="mb-7 text-center">
                <h3 class="fs-xl-10 fs-lg-8 fs-7 fw-bold font-cursive text-capitalize py-0">Attractions</h3>
            </div>
            <div class="mb-7 text-center">
                <h4 class="fw-bold text-secondary">Back to <a href="{% url 'destination_list' %}">Destinations</a>
                </h4>
            </div>

            <div class="row">
                {% for attraction in attraction_list %}
                {% if attraction.get_url in request.get_full_path %}
                <div class="col-md-4 mb-4">
                    <div class="card overflow-hidden shadow"> <img class="card-img-top" src="{{ attraction.image.url }}"
                            alt="attraction-image" />
                        <div class="card-body py-3 px-3">
                            <div class="d-flex flex-column flex-lg-row justify-content-between mb-3">
                                <h4 class="text-secondary"><a class="link-900 text-decoration-none link"
                                        href="{{ attraction.get_absolute_url }}">{{ attraction.name }}</a></h4>
                            </div>
                            <h5 class="text-muted">by {{ attraction.author }} |
                                {{ attraction.date }}</h5>

                            <div class="d-flex flex-column flex-lg-row justify-content-between mb-3">
                                {{ attraction.description }}
                            </div>
                            <div class="d-flex flex-column flex-lg-row justify-content-between mb-3">
                                {% if attraction.author.pk == request.user.pk %}
                                <a href="{% url 'attraction_edit' attraction.pk %}">Edit</a>
                                <a href="{% url 'attraction_delete' attraction.pk %}">Delete</a>
                                {% endif %}
                                <a href="{{ attraction.get_absolute_url }}">New Comment</a>
                            </div>
                            <div class="card-footer text-left text-muted">
                                {% for attractioncomment in attraction.attractioncomment_set.all %}
                                <h5 class="text-muted">{{ attractioncomment.author }} | {{ attractioncomment }}</h5>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </section>
</main>
<div class="py-5 text-center">
    <p class="mb-0 text-secondary fs--1 fw-medium">All rights reserved@darling.co </p>
</div>

</html>


<!-- ===============================================-->
<!--    JavaScripts-->
<!-- ===============================================-->
<script src="{% static 'vendors/@popperjs/popper.min.js' %}"></script>
<script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'vendors/is/is.min.js' %}"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
<script src="{% static 'vendors/fontawesome/all.min.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>

<link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&amp;family=Volkhov:wght@700&amp;display=swap"
    rel="stylesheet">
{% endblock content %}

templates/home.html
<!--templates/home.html-->
{% extends 'index.html' %}
{% block title %}Home{% endblock title%}


{% block content %}
{% if user.is_authenticated %}
<p>Welcome back, {{ user.username }}!</p>
<p>Status: {{ user.status }}</p>
<p><a href="{% url 'logout' %}">Log Out</a></p>
<p><a class="btn btn-primary btn-lg" href="{% url 'destination_list' %}" role="button">View all destinations</a></p>
<p><a class="btn btn-primary btn-lg" href="{% url 'attraction_list' %}" role="button">View all attractions</a></p>
{% else %}
<p>Welcome to Destination Darling!</p>
<p><a href="{% url 'signup' %}">Sign up</a> today to start planning your next trip!</p>

<p>Already a member? <a href="{% url 'login' %}">Log in</a></p>

{% endif %}
{% endblock content %}